apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: team02
  labels:
    Service: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
        Service: review-service
    spec:
      containers:
      - name: review-service
        image: 093322228889.dkr.ecr.ap-northeast-2.amazonaws.com/team02-review-service:latest
        ports:
        - containerPort: 8086
        envFrom:
          - configMapRef:
              name: spring-config
          - secretRef:
              name: app-secrets
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
