---
- name: Ensure review directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /home/ec2-user/services/review-src
    - /home/ec2-user/services/review

- name: Clone review from GitHub
  git:
    repo: 'https://github.com/GroomTeamProject/asdf3.git'
    dest: /home/ec2-user/services/review-src
    version: develop
    force: yes

- name: Build review on server
  shell: ./gradlew build
  args:
    chdir: /home/ec2-user/services/review-src/msa/review-service

- name: Copy built jar to deployment folder
  copy:
    src: /home/ec2-user/services/review-src/msa/review-service/build/libs/review-service.jar
    dest: /home/ec2-user/services/review/review-service.jar
    mode: '0755'

- name: Create systemd service file for review
  copy:
    dest: /etc/systemd/system/review.service
    content: |
      [Unit]
      Description=review Service
      After=network.target

      [Service]
      User=ec2-user
      ExecStart=/usr/bin/java -jar /home/ec2-user/services/review/review-service.jar
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start review
  systemd:
    name: review
    state: started
    enabled: yes
