apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: team02
  labels:
    Service: user-service   # ★ 추가
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        Service: user-service   # ★ 추가
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: user-service
        image: 093322228889.dkr.ecr.ap-northeast-2.amazonaws.com/team02-user-service:latest
        ports:
        - containerPort: 8082
        envFrom:
          - configMapRef:
              name: spring-config
          - secretRef:
              name: app-secrets
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
